### ISSUE TITLE
Enable real-time shadows on GLES2

### ISSUE THREAD

**Issue by andresan87** [asantee/ethanon#11]

**Comment by ghost** [comment]
Hi, I'd like to use Ethanon engine, it has all functionalities I need besides dynamic shadows on mobile devices. Any  chances to see this support soon?

**Comment by andresan87** [comment]
Hi, we might probably have this feature anytime in a near future. I can't give you an exact date though.

**Comment by andresan87** [comment]
Shadows and real time lights have been removed in current active mr-supersimple branches due to the fact they are not being used on current projects.
