### ISSUE TITLE
Glitches on AMD Radeon for Mac

### ISSUE THREAD

**Issue by andresan87** [asantee/ethanon#12]
More info:
http://ethanonengine.com/forums/topic/os-x-graphics-corruption-on-6750m/#post-371

**Comment by andresan87** [comment]
I think it is solved. It looks like some radeons weren't dealing well with vertex programs enabled without fragment programs being used. Solved by using fragment shaders that would emulate fixed function fragment steps.
I'm still making some tests at branch gl-no-fixed-func https://github.com/asantee/ethanon/commits/gl-no-fixed-func

If you're on a Mac and don't want to wait until 0.9.9 comes out, download the WIP versions here: https://dl.dropboxusercontent.com/u/42072982/ethanon/Ethanon-Editor-Machine-0-9-9-WIP.zip

**Comment by ScottBrooks** [comment]
I can confirm that when I use the gl-no-fixed-func branch my OSX graphical corruption is gone.  I've got a Radeon
