### ISSUE TITLE
Handle 2-byte-long UTF-8 characters correctly

### ISSUE THREAD

**Issue by andresan87** [asantee/ethanon#14]
Multibyte UTF-8-encoded characters are not being correctly handled on OSX, Android and iOS by the DrawText function.

**Comment by andresan87** [comment]
I've used the UTF8-CPP library to fix this issue on commit e204f22944be5885029a9e433bd551cfd8e9da91
It will still not work if the encoded character uses more than 2 bytes. However it is enough for many european languages (portuguese, italian, spanish and probably a lot more).

**Comment by 1l0** [comment]
Any chance to be working fine with it in future?
I have attempted to draw Japanese text converted into .fnt and .png on Ethanon and assumed that engine ignores(skips) only 2bytes characters.

**Comment by andresan87** [comment]
Hi, I believe fonts will work on most cases as long as the characters fit
in a two-byte sequence. Supposedly it is more likely to work correctly on
Windows.  Let me know how it will work for you and we can try to fix it.

2013/9/8 POPC notifications@github.com

**Comment by 1l0** [comment]
Ok, I'll report the result when I succeed. I've tested on OS X 10.8.
