### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [asantee/ethanon#27]
I would like to point out that identifiers like "[`_CPARTICLE_SCALE_HEADER_3254635787945`](https://github.com/asantee/ethanon/blob/93c28dceaff1237eaf368c957223922cf93c77b2/toolkit/Source/src/editor/ParticleScale.h#L23)" and "[`___OUTPUT_LENGTH`](https://github.com/asantee/ethanon/blob/8750a91d86dbdf9e95d5a0cccb19af6e3d778e26/toolkit/Source/src/editor/EditorBase.h#L54)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL32-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL32-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29) to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by andresan87** [comment]
You're right, this is completely messed up. Most of the editor's code is BTW. Since it is the oldest part of the engine's source, I do have plans for a complete rehash somewhere in a near future.

**Comment by andresan87** [comment]
Editor code is completely deprecated and is no longer being maintained.
