### ISSUE TITLE
OSX El Capitan - crashing

### ISSUE THREAD

**Issue by henriquekraemer** [asantee/ethanon#34]
The engine stopped working on the new OS X El Capitan, i didn't had the time to install the final version yet (im on GM). Have you tested @andresan87?

<img width="1680" alt="captura de tela 2015-10-09 as 00 00 58" src="https://cloud.githubusercontent.com/assets/822026/10384972/51937c6c-6e19-11e5-89b9-24f28f7e9e0e.png">

**Comment by andresan87** [comment]
Fixed for the current WIP build (0.9.11)
